      REAL FUNCTION display_wave()

c      ***   reconstruct the original waveform from the list of pulses


*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      30   
*     Ntuple Title:   Waveforms
*     Creation:       15/07/2013 14.23.15
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER         IDNEVT,NCHEVT,ICHEVT
      REAL            OBS(13)
*
      COMMON /PAWIDN/ IDNEVT,OBS
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL wf(10000),yorig,yref,yinc,t0,toff
      INTEGER N_wf,is,iwf
*
      COMMON /PAWCR4/ N_wf,wf,yorig,yref,yinc,t0,is,iwf,toff
*
      common/wave/wave(10000)
      vector coh_noi
      vector np
      vector amp
      vector tim
      vector sampl


c     ***   coh_noi is a vector with coherent baseline
c     ***  subtract coherent noise

      do i = 1,10000
        wave(i) = wf(i) - coh_noi(i)
      enddo

      print *,'  waveform number ',N_wf
      call hist_wave(101)

      display_wave = 1

      END
      subroutine hist_wave(idh)
c     -------------------------
      common/wave/wave(10000)

      do i=1,10000
         call hfill(idh,i-0.5,0.,wave(i))
      enddo

      end
