      REAL FUNCTION fit_rc(MIN_LEN,cut)

c      ientify a part of a wavefomr with no pulses and fit an exponential 
c      to determina RC constant, histogram the RC constants
c      the length of a snippet must be at least MIN_LEN
c      histogram 99 is an auxiliary historgram for fitting (MIN_LEN bins)
c      histogram 98 is for the fitted RC constants
 
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      30   
*     Ntuple Title:   Waveforms
*     Creation:       14/06/2013 13.41.35
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER         IDNEVT,NCHEVT,ICHEVT
      REAL            OBS(13)
*
      COMMON /PAWIDN/ IDNEVT,OBS
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL wf(10000),yorig,yref,yinc,t0,toff
      INTEGER N_wf,is,iwf
*
      COMMON /PAWCR4/ N_wf,wf,yorig,yref,yinc,t0,is,iwf,toff
*
      real par(3)
      real sigp(3)
      real pmin(3)
      real step(3)
      real pmax(3)
*
c      print *,MIN_LEN
c      return
      do i= 1 , 10000 - MIN_LEN - 100
c         print *,i
         if( i+MIN_LEN .gt. 10000) goto 200
         call hreset(99,' ')
         val = wf(i)
         do j = 1,MIN_LEN
            diff = wf(i+j+10)-val

            if(abs(diff) .le. cut) then
c              print *,i,j,cut,diff,wf(i+j-1),val
              val = wf(i+j-1)
              call hfill(99,float(j)*4.e-10,0,-val)
           else 
               i = i +j
               goto 100
            endif
         enddo

         call hfithn(99,'E+P0','NQ',3,par,step,pmin,pmax,sigp,chi2)

         call hfill(98,par(2),0,1.)

         return
         i = i + MIN_LEN
         if( i .gt. 10000) goto 200
 100     continue

      enddo
 200   continue

      fit_rc = 1

      END
