      REAL FUNCTION peak_val(il,iu)

c     ***   return the maximum value of a waveform
c     ***   in the window  il to iu
c     ***   intended to work with waveforms from sweeps_nt
c     ***   coherent noise is assumed to be in the vector
c     ***   coh_n (to be created before the invocation)

*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      30   
*     Ntuple Title:   Waveforms
*     Creation:       14/06/2013 13.41.35
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER         IDNEVT,NCHEVT,ICHEVT
      REAL            OBS(13)
*
      COMMON /PAWIDN/ IDNEVT,OBS
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL wf(10000),yorig,yref,yinc,t0,toff
      INTEGER N_wf,is,iwf
*
      COMMON /PAWCR4/ N_wf,wf,yorig,yref,yinc,t0,is,iwf,toff
*
      real wave(10000)
*
*--   Enter user code here
*
      vector coh_n

      do i=1,10000
         wave(i) = wf(i) - coh_n(i)
      enddo

c     *** find max and its position
         xmax = -999.
         do i=il,iu

            if(wave(i).gt.xmax) then
               xmax = wave(i)
               imax = i  
            endif
         enddo

      peak_val = xmax
*
      END
