      REAL FUNCTION disp_pulse(idh,thl,thu)
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      50   
*     Ntuple Title:   Pulses
*     Creation:       15/09/2013 18.37.08
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER         IDNEVT,NCHEVT,ICHEVT
      REAL            OBS(13)
*
      COMMON /PAWIDN/ IDNEVT,OBS
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL xlgate(100),gate(10),start,q(10),q_r1(10),q_r2(10),q_r3(10)
     + ,q_r4(10),t(50),t_bef(50),t_aft(50),chi_peak(50),chi_3tau(50)
     + ,ampl(50),wid66(50),wid50(50),wid33(50),q_bef(50),pulse(100,50)
      INTEGER Nwf,N_puls
*
      COMMON /PAWCR4/ Nwf,xlgate,gate,start,q,q_r1,q_r2,q_r3,q_r4,N_puls
     + ,t,t_bef,t_aft,chi_peak,chi_3tau,ampl,wid66,wid50,wid33,q_bef
     + ,pulse
*
      data icount / 0 /
*
*--   Enter user code here
*
 

      do i = 1,N_puls

      wp = 0

      if(t_bef(i).gt.5.e-8) then

      do j=30,40
         wp=wp+pulse(j,i)
      enddo

      call hfill(1000,wp,0,1.)

      endif

         if(wp.gt.thl.and.wp.lt.thu) then
            icount = icount + 1
            do j = 1,100
               call hfill(idh,j-0.5,0,pulse(j,i))
               call hfill(idh+icount,j-0.5,0,pulse(j,i))
            enddo
         endif

      enddo
      disp_pulse = 1.
*
      END
