      REAL FUNCTION uwfun()
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      60   
*     Ntuple Title:   Pulses_fin
*     Creation:       22/07/2014 14.35.24
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER         IDNEVT,NCHEVT,ICHEVT
      REAL            OBS(13)
*
      COMMON /PAWIDN/ IDNEVT,OBS
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL xlgate(500),gate(10),start,q(10),q_r1(10),q_r2(10),q_r3(10)
     + ,q_r4(10),t(100),t_bef(100),t_aft(100),chi_peak(100)
     + ,chi_3tau(100),ampl(100),wid66(100),wid50(100),wid33(100)
     + ,q_bef(100),pulse(200,100),puls_q(100)
      INTEGER Nwf,N_puls,n_puls_nq
*
      COMMON /PAWCR4/ Nwf,xlgate,gate,start,q,q_r1,q_r2,q_r3,q_r4,N_puls
     + ,n_puls_nq,t,t_bef,t_aft,chi_peak,chi_3tau,ampl,wid66,wid50,wid33
     + ,q_bef,pulse,puls_q
*

*
*--   Enter user code here
*

      uwfun = 1.
*
      END
